### ISSUE TITLE
Error running build command

### ISSUE THREAD

**Issue by crisim** [onlyurei/knockout-spa#12]
Hi, I have e problem when i try to run "npm run prod".

when I try to build it fails with 
"." is not recognized as an internal or external command, operable program or batch file

I'm on Windows 10 Pro, node 8.4.0, npm 5.3.0

just cloned the repo and executed the command.

**Comment by crisim** [comment]
this the complete log

[2017-08-22T14_32_25_928Z-debug.log.txt](https://github.com/onlyurei/knockout-spa/files/1245216/2017-08-22T14_32_25_928Z-debug.log.txt)

**Comment by onlyurei** [comment]
Windows is not officially supported.

**Comment by stephaniie2** [comment]
Even if Windows isn't supported. Can error still be fixed for Windows?

1. Can we use some tool to "fake" a none-windows enviroments? 
2. Can we install a tool that fixes this error?

**Comment by onlyurei** [comment]
@stephaniie2 you can use [cygwin](https://www.cygwin.com/) to simulate Linux environment on Windows.
