### ISSUE TITLE
Migrating knockout to vue.js

### ISSUE THREAD

**Issue by mrshawn191** [onlyurei/knockout-spa#14]
is it possible to use this framework and migrate existing code to something like vue.js? and how would that be approached?

**Comment by onlyurei** [comment]
If your legacy knockout.js based code base has mostly knockout components, then it should be relatively easy.

Here's a related nice article:
https://jes.al/2017/05/migrating-from-knockoutjs-to-vuejs/

Here's a list of Vue.js based frameworks:
https://github.com/vuejs/awesome-vue#frameworks

I have great experiences using [Nuxt.js](https://github.com/vuejs/awesome-vue#frameworks).
