### ISSUE TITLE
how use widget

### ISSUE THREAD

**Issue by baqeryan** [onlyurei/knockout-spa#3]
hi, how can i use widget or create widget for modal ?

**Comment by onlyurei** [comment]
@baqeryan if you mean third party UI widgets, you can create custom bindings and group them into files into the `/lib-ext` folder.

Here are 3 noticeable bindings lib:
https://github.com/billpull/knockout-bootstrap
https://github.com/madcapnmckay/Knockout-UI
https://github.com/kendo-labs/knockout-kendo

**Comment by baqeryan** [comment]
in project have widget/form form.js , form-input .js Where this used?

**Comment by onlyurei** [comment]
Those are from a previous project I did. I'll probably make some components out of them and put into the demo site. The original thought was for widgets to be standalone classes not requiring UI. Now that Knockout has component support it makes more sense to make components with everything included.

**Comment by onlyurei** [comment]
@baqeryan if you are interested in my use cases of the `form` widgets, checkout http://rentever.com. All the forms and form fields use them (including the filters/sorters/location checkbox/slider/etc).
