### ISSUE TITLE
Page error statusCode empty

### ISSUE THREAD

**Issue by Billybob** [onlyurei/knockout-spa#4]
Hi, when page notfound, the statusCode is empty!

work with:

> ```
> routes[key] = function () {
>     Page.loading = true;
>     var args = Array.prototype.slice.call(arguments, 0);
>     var controller = controllerName ? function (page) {
>         page.controllers[controllerName].apply(page, args);
>     } : null;
>     initPage(pageModulePath, controller);
> };
> ```

**Comment by onlyurei** [comment]
@Billybob good catch, thanks!
