### ISSUE TITLE
[API] Prefix for frontend and backend

### ISSUE THREAD

**Issue by Billybob** [onlyurei/knockout-spa#5]
It would be cool to have a prefix (eg: /api/v1/) for the backend and another (eg: /api-front/) to the frontend!
Choice would be in the API package:

```
example: {
    type: 'POST', //(['GET']|'PUT'|'PATCH'|'POST'|'DELETE') [optional]
    https: true, //(true|[false]) must call this api method via HTTPS [optional]
    url: '/example?id={id}', //([/apiPrefix/apiPackageName]|/<apiPathnameAfterPrefix>) [optional]
    target: 'frontend' //(['backend']|'frontend']) [optional]
}
```

**Comment by onlyurei** [comment]
I haven't encountered such use case before, will look into it.

**Comment by onlyurei** [comment]
@Billybob After further thought and investigations, I think a better approach would be to create and use service clients (e.g. https://github.com/floralvikings/jira-connector) if you need to access more than 1 endpoint in your app. Try to generalize the logic and conventions for different endpoints seemed not to be practical.
